#!/usr/bin/env bash
# Displays all processes (all users, even those without a TTY)
# in a human‐readable, indented tree with a seconds‐precision STARTED column.

ps auxf user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,command --forest
