#!/usr/bin/env bash
# Displays all running processes in a hierarchical, user-readable format including those without TTY

ps -eo user,pid,pcpu,pmem,vsz,rss,tty,stat,lstart,time,command --sort=start_time | \
awk 'NR==1 {sub("START", "STARTED"); print} NR>1 {print}' | \
head -50
