#!/usr/bin/env bash
# This script silently stops the 4-to_infinity_and_beyond process using gdb

pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
  {
    echo "attach $pid"
    echo "call exit(0)"
    echo "detach"
    echo "quit"
  } > /tmp/gdb_cmd

  gdb -batch -x /tmp/gdb_cmd &>/dev/null
  rm /tmp/gdb_cmd
fi
