#!/usr/bin/env bash
# Lists each non-hidden file/dir; if a name has “–”, show only what follows that first dash

for file in *; do
  if [[ "$file" == *-* ]]; then
    echo "${file#*-}"
  else
    echo "$file"
  fi
done
